version: '3'

services:

  mysql:
    image: mysql:8
    container_name: healthcare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare_db
    ports:
      - "3306:3306"

  springboot:
    build: ./backend-springboot
    container_name: healthcare-backend
    ports:
      - "8080:8080"

  ml-service:
    build: ./ml-service
    container_name: healthcare-ml
    ports:
      - "5000:5000"
